# Generated by Django 2.1 on 2019-03-26 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyitem',
            name='entry_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Entry Name'),
            preserve_default=False,
        ),
    ]
